apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  # Need to be externally accessible, so type = "LoadBalancer"
  type: LoadBalancer
  selector:
    name: result-app-pod
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80
