apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  # Type not specified as it defaults to ClusterIP
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
    - port: 6379
      targetPort: 6397
